### ISSUE TITLE
unique_together may be deprecated in the future - Consider Unique Constraints?

### ISSUE THREAD

**Issue by Finndersen** [wq/django-natural-keys#14]
Django 2.2 introduces Unique Constraint meta option which provides greater flexibility in defining uniqueness constrains. Currently django-natural-keys does not consider Unique Constraints. According to latest (3.0) Django documentation for unique_together meta option:

> Use UniqueConstraint with the constraints option instead.
> 
> UniqueConstraint provides more functionality than unique_together. unique_together may be deprecated in the future.

Therefore NaturalKeyModel should be updated to check for Unique Constraints to define natural key fields

**Comment by sheppard** [comment]
Thanks for the heads up, this is updated now.
