### ISSUE TITLE
Is rest_framework forgotten in django-natural-keys ?

### ISSUE THREAD

**Issue by oza4h07** [wq/django-natural-keys#15]
Hello,

I'm discovering django-natural-keys.
It seems djangorestframework is required for loaddata/dumpdata operations.

Does it make sense to add djangorestframework as  django-natural-keys dependencies ?

Best regards

**Comment by sheppard** [comment]
Thanks for reporting this.  The DRF integration was intended to be optional, but it was implemented in a way that effectively made it required.  I added exception handling to ensure that django-natural-keys is still usable even if DRF is not installed.
