### ISSUE TITLE
Django 3.2 `BigAutoField` IDs break natural keys for models with a single unique field

### ISSUE THREAD

**Issue by marcosox** [wq/django-natural-keys#16]
From Django 3.2 new models are now generated by default with `BigAutoField` IDs instead of `AutoField`, as written in the [release notes](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys).

This breaks the support for natural keys when using a single `unique` field in the model, because [this check inside `get_natural_key_def()`](https://github.com/wq/django-natural-keys/blob/dc406922670cb89d5f1d4ab98380e1f46c2c6ecb/natural_keys/models.py#L188) now fails.

I can write a PR which checks for `BigAutoField` too, but I don't know if someone can come up with a more generalized method.

**Comment by marcosox** [comment]
See #17 for the proposed fix

**Comment by sheppard** [comment]
Thanks, this fix is good for now.
